/**
 *
 * $Id$
 */
package petrinet.validation;


/**
 * A sample validator interface for {@link petrinet.Node}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NodeValidator {
	boolean validate();

	boolean validateMinDelay(double value);
	boolean validateMaxDelay(double value);
	boolean validateName(String value);
}
