/**
 *
 * $Id$
 */
package petrinet.validation;

import petrinet.PetriNet;

/**
 * A sample validator interface for {@link petrinet.PetriNetRelationship}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PetriNetRelationshipValidator {
	boolean validate();

	boolean validateFrom(PetriNet value);
	boolean validateTo(PetriNet value);
}
