/**
 *
 * $Id$
 */
package petrinet.validation;

import org.eclipse.emf.common.util.EList;

import petrinet.PetriNet;
import petrinet.PetriNetRelationship;

/**
 * A sample validator interface for {@link petrinet.System}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SystemValidator {
	boolean validate();

	boolean validatePetrinets(EList<PetriNet> value);
	boolean validatePetrinetrelationships(EList<PetriNetRelationship> value);
}
